/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EditTableCell: typeof import('./../components/SopBasicTable/EditTableCell.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SopBasicTable: typeof import('@seemusic/ui-components/components')['SopBasicTable']
    SopCard: typeof import('@seemusic/ui-components/components')['SopCard']
    SopDataTable: typeof import('@seemusic/ui-components/components')['SopDataTable']
    SopDataTableItem: typeof import('@seemusic/ui-components/components')['SopDataTableItem']
    SopDialog: typeof import('@seemusic/ui-components/components')['SopDialog']
    SopDrawer: typeof import('@seemusic/ui-components/components')['SopDrawer']
    SopFilterForm: typeof import('@seemusic/ui-components/components')['SopFilterForm']
    SopLayoutMain: typeof import('@seemusic/ui-components/components')['SopLayoutMain']
    SopTheHeader: typeof import('@seemusic/ui-components/components')['SopTheHeader']
    SopThes: typeof import('@seemusic/ui-components/components')['SopThes']
    SopTheSidebar: typeof import('@seemusic/ui-components/components')['SopTheSidebar']
  }
}
