/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SopCard: typeof import('@seemusic/ui-components/components')['SopCard']
    SopLayoutMain: typeof import('@seemusic/ui-components/components')['SopLayoutMain']
    SopPageHeader: typeof import('@seemusic/ui-components/components')['SopPageHeader']
  }
}
